// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: a2b01cac16
// Version Date: 2022-10-20T18:44:52Z

package main

import (
	"flag"
	//"github.com/hyperledger/fabric-contract-api-go/contractapi"
	"github.com/julkhong/blockchain-server/blockchain-service/handlers"
	//"github.com/julkhong/blockchain-server/blockchain-service/logic"
	"github.com/julkhong/blockchain-server/blockchain-service/svc/server"
	//log "github.com/sirupsen/logrus"
)

func main() {
	//amountTransferChaincode, err := contractapi.NewChaincode(&logic.AmountTransferContract{})
	//if err != nil {
	//	log.Panicf("Error creating amount transfer chaincode: %v", err)
	//}
	//if startErr := amountTransferChaincode.Start(); startErr != nil{
	//	log.Panicf("Error starting amount transfer chaincode: %v", startErr)
	//}
	// Update addresses if they have been overwritten by flags
	flag.Parse()

	cfg := server.DefaultConfig
	cfg = handlers.SetConfig(cfg)

	server.Run(cfg)
}
